import React from 'react'
import {
  BorderColor,
  Explore,
  Favorite,
  Feedback,
  Help,
  History,
  Home,
  Settings,
  Subscriptions,
} from '@mui/icons-material'

export const SidebarData = [
  {
    title: 'Home',
    path: '/',
    icon: <Home />,
    cName: 'flex justify-start items-center py-2 px-6 list-none w-60 h-14',
    type: 'link',
    accessLevel: 0,
  },
  {
    title: 'Explore',
    path: '/feed/explore',
    icon: <Explore />,
    cName: 'flex justify-start items-center py-2 px-6 list-none w-60 h-14',
    type: 'link',
    accessLevel: 0,
  },
  {
    title: 'Following',
    path: '/feed/following',
    icon: <Subscriptions />,
    cName: 'flex justify-start items-center py-2 px-6 list-none w-60 h-14',
    type: 'link',
    accessLevel: 0,
  },
  {
    cName: 'flex items-center',
    type: 'separator',
  },
  {
    title: 'History',
    path: '/feed/history',
    icon: <History />,
    cName: 'flex justify-start items-center py-2 px-6 list-none w-60 h-14',
    type: 'link',
    accessLevel: 0,
  },
  {
    title: 'Liked Plugins',
    path: '/feed/liked',
    icon: <Favorite />,
    cName: 'flex justify-start items-center py-2 px-6 list-none w-60 h-14',
    type: 'link',
    accessLevel: 0,
  },
  {
    title: 'Undecided',
    path: '/',
    icon: <Home />,
    cName: 'flex justify-start items-center py-2 px-6 list-none w-60 h-14',
    type: 'link',
    accessLevel: 3,
  },
  {
    cName: 'flex items-center',
    type: 'separator',
  },
  {
    title: 'Review',
    path: '/review',
    icon: <BorderColor />,
    cName: 'flex justify-start items-center py-2 px-6 list-none w-60 h-14',
    type: 'link',
    accessLevel: 2,
  },
  {
    cName: 'flex items-center',
    type: 'separator',
  },
  {
    title: 'Settings',
    path: '/settings',
    icon: <Settings />,
    cName: 'flex justify-start items-center py-2 px-6 list-none w-60 h-14',
    type: 'link',
    accessLevel: 0,
  },
  {
    title: 'Help',
    path: '/help',
    icon: <Help />,
    cName: 'flex justify-start items-center py-2 px-6 list-none w-60 h-14',
    type: 'link',
    accessLevel: 0,
  },
  {
    title: 'Send Feedback',
    path: 'https://github.com/jasonwynn10/PMMP-NXT',
    icon: <Feedback />,
    cName: 'flex justify-start items-center py-2 px-6 list-none w-60 h-14',
    type: 'link',
    accessLevel: 0,
  },
]
